#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

enum SimulationType {SIMULATION_STEP, SIMULATION_GENERATION};
enum SpawnerType {EVEN_DISTROBUTION};
enum EntityType {CARNIVORE, HERBIVORE, PLANT};
enum AnimalAction {NOTHING, MOVE_UPP, MOVE_DOWN, MOVE_LEFT, MOVE_RIGHT, EAT, COUNT};
enum ConsoleAction {CREATE_MAP, INIT_MAP, DELETE_MAP, VIEW_MAP, RUN_SIMULATION_STEPS, RUN_SIMULATION_GENERATIONS, COPY_MAP, OUTPUT_SIMULATION_STATUS, OUTPUT_MAPS_ONELINE};
enum OutputLevel {OUTPUT_ONELINE, OUTPUT_OVERVIEW, OUTPUT_DEEP, OUTPUT_ALL};
const int WINDOW_WIDTH = 600;
const int WINDOW_HEIGHT = 400;
const int INPUTS_PER_SQUARE = 4;
const int SENSOR_RADIUS_SQUARES = 5;
const int MAX_ENERGY = 1000;

#endif // CONSTANTS_H_INCLUDED
